# we need gcc version 5.3.1
# only available on old ubuntu
FROM ubuntu:16.04

RUN apt-get update -qq \
 && apt-get install -y --allow-downgrades \
      gcc \
      gcc-5=5.3.1-14ubuntu2 \
      binutils \
      build-essential \
      bc \
      bison \
      flex \
      libssl-dev \
      libelf-dev \
      cpp-5=5.3.1-14ubuntu2 \
      gcc-5-base=5.3.1-14ubuntu2 \
      libstdc++6=5.3.1-14ubuntu2 \
      g++ \
      g++-5=5.3.1-14ubuntu2
 && /bin/rm -rf /var/lib/apt/lists/*
