FROM golang:1.17.5-bullseye

RUN apt-get update -qq \
 && apt-get install -yq --no-install-suggests --no-install-recommends \
      software-properties-common \
      build-essential \
      git \
      wget \
      curl \
      btrfs-progs \
      go-md2man \
      iptables \
      libassuan-dev \
      libbtrfs-dev \
      libc6-dev \
      libdevmapper-dev \
      libglib2.0-dev \
      libgpgme-dev \
      libgpg-error-dev \
      libprotobuf-dev \
      libprotobuf-c-dev \
      libseccomp-dev \
      libselinux1-dev \
      libsystemd-dev \
      pkg-config \
      runc \
      uidmap \
   && /bin/rm -rf /var/lib/apt/lists/*
