# This is a basic workflow that is manually triggered

name: Docker multiarch build gcc-conmon, go-podman, gcc-v5.3.1

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:

  build-go-podman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Create image_name go-podman and tags
        run: |
          image_name=ghcr.io/${{ github.repository_owner }}/go-podman
          echo "tags=${image_name}:latest" >> ${GITHUB_ENV}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push go-podman
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ env.tags }}
          file: Dockerfile-go-podman

  build-gcc-conmon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Create image_name gcc-conmon and tags
        run: |
          gcc_conmon_image=ghcr.io/${{ github.repository_owner }}/gcc-conmon
          echo "gcc_conmon_tags=${gcc_conmon_image}:latest" >> ${GITHUB_ENV}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push gcc-conmon
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ env.gcc_conmon_tags }}
          file: Dockerfile-gcc-conmon
