# This is a basic workflow that is manually triggered

name: Docker multiarch build iotop-c

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:

  build-iotop:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create image_name iotop and tags
        run: |
          docker build -t iotop:test -f Dockerfile-iotop .

          VERSION=$(docker run iotop:test --version \
          | sed "s/iotop //")

          image_name=ghcr.io/${{ github.repository_owner }}/iotop
          echo "tags=${image_name}:${VERSION},${image_name}:latest" >> ${GITHUB_ENV}
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: ghcr.io/${{ github.repository_owner }}/iotop:${{ env.VERSION }}
        run: echo "${{ env.tags }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push iotop
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ env.tags }}
          file: Dockerfile-iotop
