# This is a basic workflow that is manually triggered

name: Docker multiarch build gcc-v5.3.1

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:

  build-gcc-5-3-1:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create image_name gcc-5-3-1 and tags
        run: |
          gcc_5_3_1_image=ghcr.io/${{ github.repository_owner }}/gcc-5-3-1
          echo "gcc_5_3_1_tags=${gcc_5_3_1_image}:latest" >> ${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push gcc-5-3-1
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ env.gcc_5_3_1_tags }}
          file: Dockerfile-gcc-5.3.1
