# This is a basic workflow that is manually triggered

name: Compile Podman and conmon

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:

  build-podman:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout podman
        uses: actions/checkout@v3
        with:
          repository: containers/podman
          ref: v4.3.1
          path: podman

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Pull docker image go-podman
        run: |
          docker pull --platform linux/arm64/v8 ghcr.io/${{ github.repository_owner }}/go-podman

      - name: Compile Podman
        run: |
          docker run --platform linux/arm64/v8 \
          --rm -v $(pwd)/podman:/podman -w /podman \
          -e CFLAGS='-static -pthread' \
          -e LDFLAGS='-s -w -static-libgcc -static' \
          -e EXTRA_LDFLAGS='-s -w -linkmode external -extldflags "-static -lm"' \
          -e BUILDTAGS='static netgo osusergo exclude_graphdriver_btrfs exclude_graphdriver_devicemapper seccomp apparmor selinux' \
          -e CGO_ENABLED=1 \
          ghcr.io/${{ github.repository_owner }}/go-podman make

      - name: Done compile Podman
        run: |
          ls -l podman/bin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Podman v4.3.1
          files: |
            ./podman/bin/podman

  build-conmon:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout conmon
        uses: actions/checkout@v3
        with:
          repository: containers/conmon
          ref: v2.1.5
          path: conmon

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Pull docker image gcc-conmon
        run: |
          docker pull --platform linux/arm64/v8 ghcr.io/${{ github.repository_owner }}/gcc-conmon

      - name: Compile conmon
        run: |
          docker run --platform linux/arm64/v8 \
          --rm -v $(pwd)/conmon:/conmon -w /conmon \
          -e CFLAGS='-static -pthread' \
          -e LDFLAGS='-s -w -static-libgcc -static' \
          -e EXTRA_LDFLAGS='-s -w -linkmode external -extldflags "-static -lm"' \
          -e CGO_ENABLED=1 \
          ghcr.io/${{ github.repository_owner }}/gcc-conmon make

      - name: Done compile conmon
        run: |
          ls -l conmon/bin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Podman v4.3.1
          files: |
            ./conmon/bin/conmon
